apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "myrs1"
spec:
  replicas: 3
  selector:
    matchLabels:
      team: prod
      tier: front
  template:
    metadata:
      labels:
        team: prod
        tier: front
    spec:
     containers:
     - name: "myc1"
       image: "vimal13/apache-webserver-php"