apiVersion: v1
kind: Pod
metadata:
  name: "mypod1"
  labels:
    app: web
    region: US
    team: test
spec:
  containers:
  - name: "myc1"
    image: "vimal13/apache-webserver-php"
---
apiVersion: v1
kind: Pod
metadata:
  name: "mypod2"
  labels:
    app: web
    region: IN
    team: test
spec:
  containers:
  - name: "myc1"
    image: "vimal13/apache-webserver-php"
  
---
apiVersion: v1
kind: Pod
metadata:
  name: "mypod3"
  labels:
    app: web
    region: US
    team: prod
spec:
  containers:
  - name: "myc1"
    image: "vimal13/apache-webserver-php"
