apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "myrs2"
spec:
  replicas: 3
  selector:
    matchLabels:
      team: prod
    matchExpressions:
    - key: tier
      operator: In
      values: [frontend]
    - key: location
      operator: In
      values: [US] 
  template:
    metadata:
      labels:
        tier: frontend
        location: US 
        team: prod
    spec:
     containers:
     - name: "myc1"
       image: "vimal13/apache-webserver-php"

    